### ISSUE TITLE
Fehlfunktion 

### ISSUE THREAD

**Issue by PInsinna** [BergWerkGIS/VoGIS-Profil-Tool#16]
Guten Tag
wir arbeiten seit einiger Zeit mit dem Vogis Profil Tool. Bei der Neuinstallation am Arbeitsplatz eines Arbeitskollegen, gibt es jetzt allerdings eine Fehlfunktion. Beim Anklicken des Menüs, öffnet sich kein Fenster mehr. Das Tool scheint wie leer zu sein. Ist dies bekannt und was könnte man unternehmen um das Problem zu beheben?
Besten dank und herzliche Grüsse

Patrick I.

**Comment by BergWerkGIS** [comment]
Na, das ist kein bekanntes Problem.
Gibt es Fehlermeldungen irgendeiner Art.

**Comment by PInsinna** [comment]
Leider gibt es keine Fehlermeldung. Es scheint so als ob der Klick ins Leere läuft. Wenn keine digitalen modelle geladen werden erscheint ja normerweise eine entsprechende Meldung mit der Frage ob man nur hektometrieren möchte... aber auch diese meldung erscheint nicht.
Mein Kollege hat sie gleiche Umgebung wie ich - drum liegt es vielleicht an bestimmten Einstellungen in QGIS?




Von meinem Samsung Galaxy Smartphone gesendet.


-------- Ursprüngliche Nachricht --------
Von: Wilhelm Berg <notifications@github.com>
Datum: 05.06.19 10:41 (GMT+01:00)
An: BergWerkGIS/VoGIS-Profil-Tool <VoGIS-Profil-Tool@noreply.github.com>
Cc: Insinna Patrick <Patrick.Insinna@llv.li>, Author <author@noreply.github.com>
Betreff: Re: [BergWerkGIS/VoGIS-Profil-Tool] Fehlfunktion  (#16)


Na, das ist kein bekanntes Problem.
Gibt es Fehlermeldungen irgendeiner Art.

**Comment by BergWerkGIS** [comment]
@PInsinna wie gesagt, kein bekannter Fehler, ich brauch etwas mehr Information, sonst kann ich nicht weiterhelfen.

* Betriebssystem? Windows, Linux, Mac? ...
* welche Version W10? Ubuntun 18.04? ...
* welche QGIS Version?
* welche PlugIn Version? die aktuelle 3.0.2?

Bzgl `keine Fehlermeldungen`:
* QGIS neu starten
* ganz rechts unten das `Log Messages` Panel einschalten
  ![image](https://user-images.githubusercontent.com/4549888/58966934-7d254100-87b3-11e9-8ad4-9538f79a7cbd.png)
* Im `Log Messages` Panel gibt es einen Reiter `VoGis` (falls er noch nicht da ist, erscheint er beim nächsten Schritt)
  ![image](https://user-images.githubusercontent.com/4549888/58967031-aa71ef00-87b3-11e9-9b01-0a2c581d14af.png)
* ProfilTool starten
* Screenshot aller `VoGis` Meldungen aus dem `Log Messages` Panel hier posten.

**Comment by PInsinna** [comment]
Besten Dank!
Ich bin unterwegs und werde morgen versuchen die angefragten Infos bereitzustellen.
Herzliche Grüsse
Patrick Insinna



Von meinem Samsung Galaxy Smartphone gesendet.


-------- Ursprüngliche Nachricht --------
Von: Wilhelm Berg <notifications@github.com>
Datum: 05.06.19 17:08 (GMT+01:00)
An: BergWerkGIS/VoGIS-Profil-Tool <VoGIS-Profil-Tool@noreply.github.com>
Cc: Insinna Patrick <Patrick.Insinna@llv.li>, Mention <mention@noreply.github.com>
Betreff: Re: [BergWerkGIS/VoGIS-Profil-Tool] Fehlfunktion  (#16)


@PInsinna<https://github.com/PInsinna> wie gesagt, kein bekannter Fehler, ich brauch etwas mehr Information, sonst kann ich nicht weiterhelfen.

  *   Betriebssystem? Windows, Linux, Mac? ...
  *   welche Version W10? Ubuntun 18.04? ...
  *   welche QGIS Version?
  *   welche PlugIn Version? die aktuelle 3.0.2?

Bzgl keine Fehlermeldungen:

  *   QGIS neu starten
  *   ganz rechts unten das Log Messages Panel einschalten
[image]<https://user-images.githubusercontent.com/4549888/58966934-7d254100-87b3-11e9-8ad4-9538f79a7cbd.png>
  *   Im Log Messages Panel gibt es einen Reiter VoGis (falls er noch nicht da ist, erscheint er beim nächsten Schritt)
[image]<https://user-images.githubusercontent.com/4549888/58967031-aa71ef00-87b3-11e9-9b01-0a2c581d14af.png>
  *   ProfilTool starten
  *   Screenshot aller VoGis Meldungen aus dem Log Messages Panel hier posten.

**Comment by PInsinna** [comment]
guten tag herr berg

hier die gewünschten informationen.
betriebssystem: windows 7 enterprise
qgis: 3.4.5 madeira
pugin: 3.0.2

ich denke nicht, dass es an den versionen liegt, da ich auf meinem pc die gleichen voraussetzunge habe. bei der allerersten installation von qgis und vogis hat das ganze funktioniert. als wir dann die beiden rastermodelle gewechselt hatten, funktionierte die erweiterung vogis nicht mehr…

danke und gruss

patrick insinna


[Unbenanntes Projekt  QGIS]

[cid:image002.png@01D53B0D.672AA7C0]

[cid:image003.png@01D53B0D.672AA7C0]

Von: Beck Olav
Gesendet: Montag, 15. Juli 2019 12:54
An: Insinna Patrick
Betreff: Unbenanntes Projekt - QGIS


[Unbenanntes Projekt  QGIS]


Von: Wilhelm Berg [mailto:notifications@github.com]
Gesendet: Mittwoch, 5. Juni 2019 17:08
An: BergWerkGIS/VoGIS-Profil-Tool
Cc: Insinna Patrick; Mention
Betreff: Re: [BergWerkGIS/VoGIS-Profil-Tool] Fehlfunktion (#16)


@PInsinna<https://github.com/PInsinna> wie gesagt, kein bekannter Fehler, ich brauch etwas mehr Information, sonst kann ich nicht weiterhelfen.

  *   Betriebssystem? Windows, Linux, Mac? ...
  *   welche Version W10? Ubuntun 18.04? ...
  *   welche QGIS Version?
  *   welche PlugIn Version? die aktuelle 3.0.2?

Bzgl keine Fehlermeldungen:

  *   QGIS neu starten
  *   ganz rechts unten das Log Messages Panel einschalten
[image]<https://user-images.githubusercontent.com/4549888/58966934-7d254100-87b3-11e9-8ad4-9538f79a7cbd.png>
  *   Im Log Messages Panel gibt es einen Reiter VoGis (falls er noch nicht da ist, erscheint er beim nächsten Schritt)
[image]<https://user-images.githubusercontent.com/4549888/58967031-aa71ef00-87b3-11e9-9b01-0a2c581d14af.png>
  *   ProfilTool starten
  *   Screenshot aller VoGis Meldungen aus dem Log Messages Panel hier posten.

**Comment by PeterDrexel** [comment]
Hallo Willy und Patrick,
liegt vermutlich daran, das QGIS einmal mit offenem Profiltool abgestürzt ist / der PC unbeabsichtigt ausgesteckt wurde oder was auch immer passiert ist...

Dann bleibt in der QGIS3.ini in der Konfiguration des Profiltools 

[vogisprofiltoolmain]
dpi=72
savepath=D:/
scale=1:500
isopen=**true**

stehen statt 
isopen=**false**

Beim nächsten Start von QGIS 3 lässt sich das Profiltool dann nicht mehr öffnen.
Lösung:
in C:\Users\*****\AppData\Roaming\QGIS\QGIS3\profiles\default\QGIS\QGIS3.ini
die ensprechende Zeile ändern.

Liebe Grüße
Peter

**Comment by PInsinna** [comment]
hallo peter

vielen dank! ich werde das nach meinen ferien gleich probieren und  melde mich dann wieder!

beste grüsse aus vaduz

patrick

Von: PeterDrexel [mailto:notifications@github.com]
Gesendet: Donnerstag, 18. Juli 2019 15:42
An: BergWerkGIS/VoGIS-Profil-Tool
Cc: Insinna Patrick; Mention
Betreff: Re: [BergWerkGIS/VoGIS-Profil-Tool] Fehlfunktion (#16)


Hallo Willy und Patrick,
liegt vermutlich daran, das QGIS einmal mit offenem Profiltool abgestürzt ist / der PC unbeabsichtigt ausgesteckt wurde oder was auch immer passiert ist...

Dann bleibt in der QGIS3.ini in der Konfiguration des Profiltools

[vogisprofiltoolmain]
dpi=72
savepath=D:/
scale=1:500
isopen=true

stehen statt
isopen=false

Beim nächsten Start von QGIS 3 lässt sich das Profiltool dann nicht mehr öffnen.
Lösung:
in C:\Users*****\AppData\Roaming\QGIS\QGIS3\profiles\default\QGIS\QGIS3.ini
die ensprechende Zeile ändern.

Liebe Grüße
Peter

**Comment by BergWerkGIS** [comment]
danke @PeterDrexel
