### ISSUE TITLE
Werkzeug, doppelt; Fehler beim Ausführen des Werkzeugs

### ISSUE THREAD

**Issue by Jannik-Schilling** [BergWerkGIS/VoGIS-Profil-Tool#27]
Interessanterweise gibt es das Werkzeug bei mit zwei Mal (nach normaler Installation über den QGIS-Plugin-Manager).
![grafik](https://github.com/BergWerkGIS/VoGIS-Profil-Tool/assets/54308008/c2e2930f-64a0-4d73-a7a0-27477dabcd8c)

Beim Ausführen des oberen Werkzeugs passiert gar nichts. Bei Klick auf den unteren Button tritt folgender Fehler auf:

```
TypeError: QgsRubberBand(): argument 2 has unexpected type 'bool' 
Traceback (most recent call last):
  File ".../AppData/Roaming/QGIS/QGIS3\profiles\en/python/plugins\VoGisProfilTool\vogisprofiltoolmain.py", line 127, in run
    self.dlg = VoGISProfilToolMainDialog(self.iface, self.settings)
  File ".../AppData/Roaming/QGIS/QGIS3\profiles\en/python/plugins\VoGisProfilTool\vogisprofiltoolmaindialog.py", line 102, in __init__
    self.rubberband = QgsRubberBand(self.canvas, self.polygon)
TypeError: QgsRubberBand(): argument 2 has unexpected type 'bool'


Python-Version: 3.9.18 (heads/master:5eba59e, Feb  1 2024, 20:02:10) [MSC v.1929 64 bit (AMD64)] 
QGIS-Version: 3.34.4-Prizren Prizren, decd43dc 
```

**Comment by wilhelmberg** [comment]
@Jannik-Schilling ich denke das hat damit zu tun, dass das Werkzeug inzwischen "ziemlich" veraltet ist und wohl nicht mehr mit aktuellen QGIS Versionen funktioniert.
Das Plugin war seinerzeit eine Auftragsarbeit und das letzte Update war vor mehr als 5 Jahren.
Leider habe ich keine Ressourcen, um das Plugin in meiner Freizeit auf einen aktuellen Stand zu bringen.

Ich empfehle die Verwendung des Profil Werkzeuges, welches standardmäßig in QGIS vorhanden ist:
https://docs.qgis.org/3.34/en/docs/user_manual/map_views/elevation_profile.html
