### ISSUE TITLE
Please make it translatable

### ISSUE THREAD

**Issue by pcav** [BergWerkGIS/VoGIS-Profil-Tool#3]
Thanks

**Comment by BergWerkGIS** [comment]
@pcav  Could you try again?

Now GUI should default to `en` automatically, if your system locale is __not__ `de`.
So, no need to override locale in QGIS settings.

You can get the latest zip here:
https://github.com/BergWerkGIS/VoGIS-Profil-Tool/releases

Or add this (https://raw.githubusercontent.com/BergWerkGIS/VoGIS-Profil-Tool/intersection/plugins.xml) as a new PlugIn Repo in your QGIS settings.
Then you will get automatic updates as soon as I push a new tag to Github.
But the intersection branch will soon be merged into master and published on the offical QGIS repo.
So this might not be worth the effort.

**Comment by pcav** [comment]
Il 09/02/2015 13:38, Wilhelm Berg ha scritto:
> @pcav <https://github.com/pcav> Could you try again?

very short of time now, could you please upload the new version and let
me know?
all the best, and thanks.

-- 
Paolo Cavallini - www.faunalia.eu
QGIS & PostGIS courses: http://www.faunalia.eu/training.html
*New course* "QGIS for naturalists":
http://www.faunalia.eu/en/nat_course.html

**Comment by BergWerkGIS** [comment]
Ok!

**Comment by fdgian** [comment]
Hi, I just downladed the plugin on QGIS 3.4.7 there is still a line in gernam in the define profile mask, "zusammenhängende linien verbinden" instead of "merge connected lines"

**Comment by BergWerkGIS** [comment]
Thanks for spotting this @fdgian 
I've opened a new issue #15 and it will be included in the next release.
