### ISSUE TITLE
Input Vector Geometry Not Valid

### ISSUE THREAD

**Issue by charparr** [BergWerkGIS/VoGIS-Profil-Tool#5]
Hello,

I am trying to use your tool using the "Derive Profile from Line Features" option. When I use the tool I receive an error box reading: "PREPARE ERROR - 
Original features:
Vector input not valid!
Please check message log and
"Check Geometry Validity Tool"

and I am unable to produce any profiles.

Do you have any ideas as to what may be wrong with my input vector?

I am running QGIS 2.8.1 Wien.

Thanks!

![error](https://cloud.githubusercontent.com/assets/7774271/8584250/2add6168-2581-11e5-8e87-9014b8b85d49.png)

**Comment by BergWerkGIS** [comment]
Hello @charparr please check your input vector with `Vector -> Geometry Tools -> Check Geometry Validity...`
1. Does this show any information why the profile line is invalid?
2. Can you provide a download of the line, that I can take a look?

**Comment by charparr** [comment]
Hey, thanks for the reply! I double checked my geometry using the tools you suggested - turns out I had some redundant vertices that were invisible to the naked eye, thanks for the suggestion. I should have figured it out on my own. I am finding the profile tool very useful. You can go ahead and close this issue.

**Comment by BergWerkGIS** [comment]
Perfect! Thanks for letting me know.

**Comment by skyflying** [comment]
Hello, I still have this issue, now for more than two line in one files/later.

Do you have any ideas as to what may be wrong with my input vector?

QGIS ver 3.16 and 3.22
