### ISSUE TITLE
error

### ISSUE THREAD

**Issue by krisboers** [BergWerkGIS/VoGIS-Profil-Tool#9]
One of our employees gets following error when he tries to make a profile:
File "C:/Users/kevinf/.qgis2/python/plugins\VoGisProfilTool\vogisprofiltoolmaindialog.py", line 194, in profiles_finished
dlg = VoGISProfilToolPlotDialog(self.iface, self.settings, profiles, intersections)
File "C:/Users/kevinf/.qgis2/python/plugins\VoGisProfilTool\vogisprofiltoolplot.py", line 104, in init
plt_toolbar = matplotlib.backends.backend_qt4agg.NavigationToolbar2QTAgg(self.plt_widget, self.ui.IDC_frPlot)
AttributeError: 'module' object has no attribute 'NavigationToolbar2QTAgg'

Any ideas?

**Comment by kikislater** [comment]
It's related to new version of matplotlib and listed here :

https://github.com/BergWerkGIS/VoGIS-Profil-Tool/issues/6

There is solution in this thread

**Comment by krisboers** [comment]
ok, thx. we'll try that
